version: '3.8'

services:
  app:
    image: musify-backend:latest
    container_name: musify-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # All environment variables should be provided via .env file or secrets management
      ENVIRONMENT: production
    env_file:
      - .env
    volumes:
      - /var/musify/uploads:/app/uploads
      - /var/musify/logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - musify-network

  nginx:
    image: nginx:alpine
    container_name: musify-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - /var/musify/static:/usr/share/nginx/html/static:ro
    depends_on:
      - app
    networks:
      - musify-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  musify-network:
    driver: bridge