#!/bin/bash

echo "Valkey (Redis Fork) Installation Guide for Manjaro Linux"
echo "========================================================"
echo ""
echo "Valkey is the open-source fork of Redis, maintaining full compatibility"
echo ""

# Check if running on Manjaro
if [ -f /etc/manjaro-release ]; then
    echo "✓ Detected Manjaro Linux"
else
    echo "⚠️  This script is designed for Manjaro Linux"
fi

echo ""
echo "Option 1: Install Valkey from AUR"
echo "---------------------------------"
echo "# Using yay"
echo "yay -S valkey"
echo ""
echo "# Or using pamac"
echo "pamac install valkey"
echo ""

echo "Option 2: Install Redis (still available)"
echo "-----------------------------------------"
echo "# Redis package may still be available"
echo "sudo pacman -S redis"
echo ""

echo "Option 3: Use Redis-compatible Valkey"
echo "-------------------------------------"
echo "# Valkey is 100% Redis-compatible, so you can use it as a drop-in replacement"
echo ""

echo "After Installation:"
echo "==================="
echo ""
echo "1. Start Valkey service:"
echo "   sudo systemctl start valkey"
echo ""
echo "2. Enable Valkey to start on boot:"
echo "   sudo systemctl enable valkey"
echo ""
echo "3. Check Valkey status:"
echo "   sudo systemctl status valkey"
echo ""
echo "4. Test connection (uses redis-cli):"
echo "   redis-cli ping"
echo "   # or"
echo "   valkey-cli ping"
echo "   (Should return 'PONG')"
echo ""

echo "Configuration:"
echo "=============="
echo ""
echo "Valkey config file location: /etc/valkey/valkey.conf"
echo "Note: Valkey uses the same configuration format as Redis"
echo ""
echo "Common configurations to modify:"
echo "- bind 127.0.0.1 ::1  # Listen only on localhost"
echo "- port 6379           # Default port (same as Redis)"
echo "- maxmemory 256mb     # Set memory limit"
echo "- maxmemory-policy allkeys-lru  # Eviction policy"
echo ""

echo "Quick Install Commands:"
echo "======================="
echo ""
echo "# For Valkey (if available in AUR):"
echo "yay -S valkey"
echo "sudo systemctl enable --now valkey"
echo "redis-cli ping"
echo ""
echo "# Or use Redis (if Valkey not available):"
echo "sudo pacman -Syu && sudo pacman -S redis"
echo "sudo systemctl enable --now redis"
echo "redis-cli ping"
echo ""

echo "Compatibility Note:"
echo "==================="
echo "Valkey is 100% compatible with Redis protocol and commands."
echo "Your Musify backend will work with Valkey without any code changes!"
echo ""
echo "The Redis client libraries (like Jedis) work perfectly with Valkey."
echo ""

echo "Docker Alternative:"
echo "==================="
echo "If Valkey package is not available, use Docker:"
echo ""
echo "# Run Valkey in Docker"
echo "docker run -d -p 6379:6379 --name valkey valkey/valkey:latest"
echo ""
echo "# Or use Redis Docker image"
echo "docker run -d -p 6379:6379 --name redis redis:alpine"
echo ""

echo "Verify Installation:"
echo "===================="
echo ""
echo "# Check if service is running"
echo "sudo systemctl status valkey || sudo systemctl status redis"
echo ""
echo "# Test connection"
echo "redis-cli ping"
echo ""
echo "# Check server info"
echo "redis-cli INFO server"
echo ""

echo "For Musify Backend:"
echo "==================="
echo "No changes needed! Valkey uses the same protocol as Redis."
echo "Your existing configuration will work:"
echo ""
echo "REDIS_ENABLED=true"
echo "REDIS_HOST=localhost"
echo "REDIS_PORT=6379"
echo ""