#!/bin/bash

echo "Redis Installation Guide for Manjaro Linux"
echo "=========================================="
echo ""

# Check if running on Manjaro
if [ -f /etc/manjaro-release ]; then
    echo "✓ Detected Manjaro Linux"
else
    echo "⚠️  This script is designed for Manjaro Linux"
fi

echo ""
echo "Option 1: Install from Official Manjaro Repository (Recommended)"
echo "--------------------------------------------------------------"
echo "Run these commands:"
echo ""
echo "# Update package database"
echo "sudo pacman -Syu"
echo ""
echo "# Install Redis"
echo "sudo pacman -S redis"
echo ""

echo "Option 2: Install from AUR (Latest version)"
echo "------------------------------------------"
echo "If you want the absolute latest version:"
echo ""
echo "# Using yay (AUR helper)"
echo "yay -S redis"
echo ""
echo "# Or using pamac"
echo "pamac install redis"
echo ""

echo "After Installation:"
echo "==================="
echo ""
echo "1. Start Redis service:"
echo "   sudo systemctl start redis"
echo ""
echo "2. Enable Redis to start on boot:"
echo "   sudo systemctl enable redis"
echo ""
echo "3. Check Redis status:"
echo "   sudo systemctl status redis"
echo ""
echo "4. Test Redis connection:"
echo "   redis-cli ping"
echo "   (Should return 'PONG')"
echo ""

echo "Configuration:"
echo "=============="
echo ""
echo "Redis config file location: /etc/redis/redis.conf"
echo ""
echo "Common configurations to modify:"
echo "- bind 127.0.0.1 ::1  # Listen only on localhost"
echo "- port 6379           # Default port"
echo "- maxmemory 256mb     # Set memory limit"
echo "- maxmemory-policy allkeys-lru  # Eviction policy"
echo ""

echo "Quick Install Commands:"
echo "======================="
echo ""
echo "# Copy and paste these commands to install and start Redis:"
echo ""
echo "sudo pacman -Syu && sudo pacman -S redis"
echo "sudo systemctl enable --now redis"
echo "redis-cli ping"
echo ""

echo "Verify Installation:"
echo "===================="
echo ""
echo "# Check if Redis is installed"
echo "pacman -Q redis"
echo ""
echo "# Check Redis version"
echo "redis-server --version"
echo ""
echo "# Check if Redis is running"
echo "ps aux | grep redis"
echo ""

echo "Troubleshooting:"
echo "================"
echo ""
echo "If Redis fails to start:"
echo "1. Check logs: sudo journalctl -u redis -n 50"
echo "2. Check config: sudo redis-server /etc/redis/redis.conf --test-config"
echo "3. Check port availability: sudo lsof -i :6379"
echo ""

echo "Uninstall (if needed):"
echo "======================"
echo "sudo systemctl stop redis"
echo "sudo systemctl disable redis"
echo "sudo pacman -R redis"
echo ""